### ISSUE TITLE
Subject line with spanish characters V2 .vs. V3

### ISSUE THREAD

**Issue by nahanmail** [sendgrid/sendgrid-csharp#308] opened 2016-08-22 15:45 UTC
#### Issue Summary

When using V2 SendGridMessage and assigning a value to the subject property that contains a spanish character, the email subject line shows properly in Outlook. "Información" is the test word I have been using. In V3 SendGridHelpers.Mail and assigning a value to the subject property the letter with the acute above the "o" shows up with a black filled diamond containing a white question mark.
Maybe I am overlooking something simple, but any help would be appreciated. The body content seems to work fine.

Also, do you have a complete list of StatusCodes values returned. So far I am only seeing "BadRequest" or "Accepted".
#### Steps to Reproduce
1. Send mail through SendGridMessage V2 with subject line outlined above
2. Send mail through SendGridHelpers.Mail V3 with subject line outlined above
3. See attached document with sample of V2 and V3 from outlook
#### Technical details:
- sendgrid-csharp Version: 8.0.2.0
- .NET Version: 4.5.2
  [V2V3subjectline_20160822.docx](https://github.com/sendgrid/sendgrid-csharp/files/430531/V2V3subjectline_20160822.docx)

**Comment by thinkingserious** [comment] 2016-08-22 22:58
Thanks for the bug report @nahanmail, we will investigate.

**Comment by nahanmail** [comment] 2016-09-26 19:17
Trying to figure out a work around for this issue and further trouble shooting. Found the subject line shows correctly without any custom args, but when you add custom args with either the helper class or JSON it no longer formats correctly. Rolling out to test for client this week. We have to use custom args for tracking. Do I have to use V2?

**Comment by thinkingserious** [comment] 2016-09-26 21:37
@nahanmail,

I would suggest that, since I can not guarantee we will have it fixed this week.

**Comment by nahanmail** [comment] 2016-09-26 21:39
Ok, after trying different things with add custom arguments, I started researching subject line encoding. Found RFC1342 with the use of =?charset?encoding?encoded-text?=, so I tried with subject line and SendGrid dropped them because of invalid header. Kept searching and found that String.Normalize worked and worked whether or not I had custom arguments. 

EmailSubject is a string from value from a class.
mail.Subject = EmailSubject.Normalize(System.Text.NormalizationForm.FormKD);

This is working so I should be good with this work around for now.

Thanks.

**Comment by thinkingserious** [comment] 2016-09-27 15:40
Thanks for sharing the workaround with us!

Please email us at dx@sendgrid.com with your mailing address and T-shirt size so we can send you some swag.

**Comment by steenodegaard** [comment] 2016-11-18 10:20
I have the same issue. This workaround does not fix it for me. I found that the course of the issue is that I add some custom args. After doing so, Sendgrid fails to UTF-8 encode the subject part of the email. comparison:

**With**: 
Subject: Invitation til deltagelse i sp???rgeskemaunders???gelse

**Without**:
Subject: =?UTF-8?B?SW52aXRhdGlvbiB0aWwgZGVsdGFnZWxzZSBpIHNww7hyZ2Vza2VtYXVuZGVycw==?=
 =?UTF-8?B?w7hnZWxzZQ==?=

**Comment by snaegeli** [comment] 2016-11-23 19:53
I have the same issue with German "Umlaute" (öäü). They don't work anymore in version 8.0.5 while they have worked in 6.3.4. The workaround above does fix it for some email accounts but breaks it for other accounts (e.g. Exchange accounts) using Outlook.

**Comment by awwa** [comment] 2016-11-24 01:39
It seems that the problem is not the library bug. Because I could reproduce without the library. 
Here is my workaround. I hope this will be help.

My workaround is adding substitution key which value is empty in the Subject header when you use `substitutions` with non-ASCII character Subject. Here is full body of the request. I think you can create the body with the mail helper.

```
{
  "personalizations": [
    {
      "to": [
        {
          "email": "recipient@example.com"
        }
      ],
      "subject": "Información%subkey%",
      "substitutions": {
      	"%subkey%": ""
      }
    }
  ],
  "from": {
    "email": "sender@example.com"
  },
  "content": [
    {
      "type": "text/plain",
      "value": "Hello"
    }
  ]
}
```

**Comment by steenodegaard** [comment] 2016-11-24 12:24
Thank you awwa. I can confirm that the workaround works. Here is the C# code:

```
message.Subject = subject + "%subkey%";
Personalization personalization = new Personalization();
personalization.AddSubstitution("%subkey%", "");
message.AddPersonalization(personalization);
```

**Comment by snaegeli** [comment] 2016-11-24 19:42
Great, that workaround fixed it. Thanks!

**Comment by mbernier** [comment] 2016-12-12 17:26
I have submitted this to our team and we will be working to get it fixed. Thanks!

**Comment by Bertram25** [comment] 2020-03-31 13:49
To add more to this subject, it seems SendGrid (or subsequent services) is somehow encoding subjects only partially.

While using SendGrid v9.12.6 on .Net core 3.1 and sending an email with a french subject:
`"Votre thérapeute a modifié votre compte."`
The subject gets encoded that way:
`Subject: Votre =?UTF-8?B?dGjDqXJhcGV1dGUgYSBtb2RpZmnDqQ==?= votre compte.`
which gives a broken subject.
Normalizing the subject string does change the subject response but still always give a partially encoded and broken title.

I do believe that encoding the full subject instead of encoding part of it will fix the bug in this specific case, if it can be of any help.
Cheers,

**Comment by eshanholtz** [comment] 2020-09-02 00:05
Closing this as it has been marked a non-library issue.

**Closed by eshanholtz** 2020-09-02 00:05 UTC
Labels: difficulty: unknown or n/a, type: non-library issue
