### ISSUE TITLE
Sendgrid attachment missing when filename has utf-8 characters

### ISSUE THREAD

**Issue by walmon** [sendgrid/sendgrid-csharp#296] opened 2016-08-02 19:42 UTC
#### Issue Summary

When using Sendgrid SDK 6.3.4 on a console application, in an attachment if a filename has especial characters, the email will be delivered without attachment.

No errors logged, just the email arriving without the attachment.
#### Steps to Reproduce

For example:
myMessage.AddAttachment(file,  "Información.csv"); // won't work
myMessage.AddAttachment(file,  "Informacion.csv"); // will work
#### Technical details:
- sendgrid-csharp Version: 6.3.4 
- .NET Version: 4.6

**Comment by thinkingserious** [comment] 2016-08-04 15:59
Hello @walmon,

Thanks for reporting this issue!

I have verified that this is not an API issue. This issue is with this library. 

I have added this to our backlog to fix.

With Best Regards,

Elmer

**Comment by jirihelmich** [comment] 2016-09-02 11:38
I might have another version of this issue. When sending an attachment with a filename "Reservation Report 1. 9. 2016 0:00:00 - 3. 9. 2016 0:00:00.xlsx", an e-mail with the filename "00.xlsx" is delivered.

It's a bit strange that it's the part of the filename that comes after the last header name:value separator (colon)... Is it the lib, the API, or is it me? Thanks!

**Comment by thinkingserious** [comment] 2016-09-02 17:42
Thanks for the additional feedback @jirihelmich. I'll add your vote to this task to help it rise faster in our backlog queue.

**Comment by jirihelmich** [comment] 2016-09-05 13:29
Thanks. Based on this, we retrospectively identified some more issues from the past related to this. We were experiencing lost attachments with no good reason in the e-mail source code. We thought it's SPF + spamfilter, throwing away PDFs (like bills, etc.), but as our attachments are localized and may contain customer name (e.g. Chinese, Japanese, Greek), this seem to be the real issue.

Do you have any estimates? Or, is there any way how we could help to fix this? Otherwise, we would have to somehow hack our system and implement transliteration to ASCII, but that's probably more work than fixing this.

Thanks for any further information.

**Comment by thinkingserious** [comment] 2016-09-07 02:21
Thanks @jirihelmich,

All of this information should help when it comes time for me to dig in on this one. I've added more votes to this issue based on the +1's on your previous comment.

**Comment by jirihelmich** [comment] 2016-09-09 07:39
Hi, thanks for the additional information.

Just wanted to confirm that once we implemented a workaround (transliteration and sanitize of "wild" characters), the attachments are now going through. Our Greek customers are now a bit happier :-)

**Comment by thinkingserious** [comment] 2016-09-09 17:54
Thanks for the update @jirihelmich,

I see that there are some more +1s on this issue. I've added those to the ticket in our backlog.

**Comment by vanillajonathan** [comment] 2017-03-09 16:22
I looked at the code:
* [SendGridMessage.cs#L936](https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/Helpers/Mail/SendGridMessage.cs#L936) (The `AddAttachment` method)
* [Attachment.cs](https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/Helpers/Mail/Model/Attachment.cs)

But nothing there stands out, it's just normal string assignments.

The `SendGridMessage` instance (which contains the attachments) gets passed to the [`SendEmailAsync`](https://github.com/sendgrid/sendgrid-csharp/blob/2bc388565671dd14234b934e0424689b4ac92d18/src/SendGrid/SendGridClient.cs#L389) method in the `SendGridClient` class which seemingly properly serializes it to a JSON string (using the [Serialize](https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/Helpers/Mail/SendGridMessage.cs#L1404) method) before it gets passed to the [`RequestAsync`](https://github.com/sendgrid/sendgrid-csharp/blob/2bc388565671dd14234b934e0424689b4ac92d18/src/SendGrid/SendGridClient.cs#L307) method.

```cs
var message = new SendGridMessage();
message.AddAttachment("Filename_foo", "content");
message.AddAttachment("Filename_åäö", "content");
var serialized = message.Serialize();
```

Output:
```json
{
  "attachments": [
    {
      "content": "content",
      "filename": "Filename_foo"
    },
    {
      "content": "content",
      "filename": "Filename_åäö"
    }
  ]
}
````

The JSON serialized string which gets passed to `RequestAsync` is used to create a seemingly proper [`StringContent`](https://github.com/sendgrid/sendgrid-csharp/blob/2bc388565671dd14234b934e0424689b4ac92d18/src/SendGrid/SendGridClient.cs#L359).

```cs
var content = new StringContent(serialized, Encoding.UTF8, null);
var contentString = content.ReadAsStringAsync().Result;
```

Which is still intact:
```json
{"attachments":[{"content":"content","filename":"Filename_foo"},{"content":"content","filename":"Filename_åäö"}]}
```

This is used to construct a `HttpRequestMessage`.

```cs
var request = new HttpRequestMessage
{
    Method = new HttpMethod("POST"),
    Content = content
};

var requestContent = request.Content.ReadAsStringAsync().Result;
```

It is still intact:
```json
{"attachments":[{"content":"content","filename":"Filename_foo"},{"content":"content","filename":"Filename_åäö"}]}
```

Then when I send it using `HttpClient` it is still intact.

# Code
```c
using System;
using System.Net.Http;
using System.Text;
using SendGrid.Helpers.Mail;

namespace SendGridClient
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var message = new SendGridMessage();
            message.AddAttachment("Filename_foo", "content");
            message.AddAttachment("Filename_åäö", "content");

            var serialized = message.Serialize();
            var content = new StringContent(serialized, Encoding.UTF8, null);
            var contentResult = content.ReadAsStringAsync().Result;

            var request = new HttpRequestMessage
            {
                Method = new HttpMethod("POST"),
                Content = content
            };

            var requestContent = request.Content.ReadAsStringAsync().Result;

            using (var client = new HttpClient())
            {
                // You can check at http://requestb.in/xayqitxa?inspect
                client.BaseAddress = new Uri("http://requestb.in/xayqitxa");
                client.DefaultRequestHeaders.Accept.Clear();
                var foo = client.SendAsync(request).Result;
            }

            Console.WriteLine(requestContent);
            Console.ReadLine();
        }
    }
}
```

So I am no closer than before, but perhaps this can hint someone. I might look more tomorrow if I got time.

**Comment by thinkingserious** [comment] 2017-03-09 17:42
@vanillajonathan,

I just tested with success with the following code using the latest v9 C# SDK:

```csharp
using SendGrid;
using SendGrid.Helpers.Mail;
using System;
using System.Threading.Tasks;

namespace Example
{
	internal class Example
	{
		private static void Main()
		{
			Execute().Wait();
		}

		static async Task Execute()
		{
			var apiKey = Environment.GetEnvironmentVariable("SENDGRID_API_KEY");
			var client = new SendGridClient(apiKey);
			var msg = new SendGridMessage()
			{
				From = new EmailAddress("dx@sendgrid.com", "DX Team"),
				Subject = "Hello World from the SendGrid CSharp SDK!",
				PlainTextContent = "Hello, Email!",
				HtmlContent = "<strong>Hello, Email!</strong>"
			};
			msg.AddTo(new EmailAddress("elmer.thomas@sendgrid.com", "Test User"));
			byte[] excelArray = System.IO.File.ReadAllBytes(@"/Users/ethomas/Downloads/Book 2.xlsx");
			string base64ExcelRepresentation = Convert.ToBase64String(excelArray);
			msg.AddAttachment("Sheet_åäö.xlsx", base64ExcelRepresentation, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
			Console.WriteLine(msg.Serialize());
			var response = await client.SendEmailAsync(msg);
			Console.WriteLine(response.Body.ReadAsStringAsync().Result);
			Console.ReadLine();
		}
	}
}
```

**Comment by vanillajonathan** [comment] 2017-03-10 12:29
Anyone affected by the big should try to upgrade to the latest version of the library.
As a workaround you can strip out the diacritics (accents) from the filename.
http://www.levibotelho.com/development/c-remove-diacritics-accents-from-a-string

@thinkingserious,
I ran your code using v9 C# SDK and the library seems to behave as intended.
I specified a `host` parameter to the constructor in `SendGridClient` to make it POST the request to RequestBin and the data arrives with the proper filenames. As far as I can tell the library works as intended and the bug does not apply to v9.

Perhaps time to close the bug as fixed?

**Comment by thinkingserious** [comment] 2017-03-10 19:40
Thanks for the confirmation @vanillajonathan 

I will close this ticket.

If anyone else continues to experience issues, please open a new ticket. 

Thanks!

**Closed by thinkingserious** 2017-03-10 19:40 UTC
Labels: status: help wanted, type: bug

**Comment by jeetbhalani** [comment] 2018-07-14 16:40
@thinkingserious 
it works for me. 

Thank you so much!

**Comment by thinkingserious** [comment] 2018-07-24 00:53
Thanks for verifying @jeetbhalani!

**Comment by madanpragada4** [comment] 2019-11-19 06:22
Hello @thinkingserious sending the file name with accents still not working. Please do necessary changes to handle it. I spent lot of time and found a solution to send accents with UTF-8 base64 encode as 
"=?UTF-8?B?" . base64_encode( $file_name )  .  "?="
Which solved my problem.
