### ISSUE TITLE
Allow ; in ContentType for attachment header to support calendar invites

### ISSUE THREAD

**Issue by chr22** [sendgrid/sendgrid-csharp#386] opened 2017-01-20 07:58 UTC
To support calendar invites (ics files) in Outlook the Content Type property in the attachements header needs to have both "text/calendar" and "method=REQUEST" separated by a semicolon but SendGrid returns the error below when you set a semicolon in the Type param:

"The attachment type cannot contain ';', or CRLF characters. field:attachments.0.type"

```C#
var sendGridAttachment = new Attachment();
sendGridAttachment.Content = base64Invite;
sendGridAttachment.Type = "text/calendar; charset=UTF-8; method=REQUEST";
sendGridAttachment.Filename = "invite.ics";
```

* sendgrid-csharp Version: 8.0.5.0
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment] 2017-01-24 23:32
Hello @chr22,

Please follow this thread for updates on this issue: https://github.com/sendgrid/sendgrid-php/issues/250

Currently, the issue is in our backlog and your vote has been added. Thanks!

**Comment by eshanholtz** [comment] 2020-09-02 00:09
Closing this as it has been marked a non-library issue.

**Closed by eshanholtz** 2020-09-02 00:09 UTC
Labels: difficulty: unknown or n/a, type: non-library issue
