### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by walmon** [sendgrid/sendgrid-csharp#237] opened 2016-06-16 00:09 UTC
#### Issue Summary

ASP.NET Web API 4.5.2 Application, sending email added c# libraries paste this code

#### Steps to Reproduce

1. Install dlls from nuget Install-Package SendGrid
2. added example code

 String apiKey = Environment.GetEnvironmentVariable("SENDGRID_APIKEY", EnvironmentVariableTarget.User);
            dynamic sg = new SendGridAPIClient(apiKey);

            Email from = new Email("test@example.com");
            String subject = "Hello World from the SendGrid CSharp Library";
            Email to = new Email("test@example.com");
            Content content = new Content("text/plain", "Textual content");
            Mail mail = new Mail(from, subject, to, content);

            dynamic response = sg.client.mail.send.post(requestBody: mail.Get());

then this never gets a response, sometimes deliver messages

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment] 2016-06-16 00:19
Thanks @walmon,

We appreciate the issue!

This issue is a duplicate of https://github.com/sendgrid/sendgrid-csharp/issues/235, please follow that issue as I'll likely be looking into this issue tomorrow.

I'm thinking our examples need to be updated to account for the async calls in the HTTP client: https://github.com/sendgrid/csharp-http-client/blob/master/CSharpHTTPClient/Client.cs#L264

**Closed by thinkingserious** 2016-06-16 00:19 UTC
Labels: status: duplicate

**Comment by walmon** [comment] 2016-06-16 00:21
What is the work around? In previous versions the c# sdk was working, Im about to purchase the service but cant get it to work.

**Comment by thinkingserious** [comment] 2016-06-16 00:22
You can use: https://www.nuget.org/packages/Sendgrid/6.3.4

Thanks and welcome to SendGrid!

**Comment by walmon** [comment] 2016-06-16 00:23
Awesome! Thanks!
