### ISSUE TITLE
Response contains HTTP code 200 and error in body if client sends an email when disconnected from Internet

### ISSUE THREAD

**Issue by chumakov-ilya** [sendgrid/sendgrid-csharp#358] opened 2016-10-25 15:39 UTC
#### Issue Summary

When I try to send an email without network connection to remote SMTP server, a response contains `200 OK` in `StatusCode` and `HttpRequestException` in `Body`. I think it denies basic HTTP principles and such behaviour is completely unclear. I propose to throw a real exception. If impossible, the code from 4xx-5xx range should be used.
#### Steps to Reproduce

```
var sg = new SendGridAPIClient("my_api_key");

Mail mail = new Mail(from, subject, to, content);

//disconnect from Internet before executing this line
var response = await sg.client.mail.send.post(requestBody: mail.Get());

//writes "OK"
Console.WriteLine(response.StatusCode);

//writes ".NET HttpRequestException, raw message: An error occurred while sending the request"
Console.WriteLine(response.Body.ReadAsStringAsync().Result);
```
#### Technical details:
- sendgrid-csharp Version: v8.0.5
- .NET Version: 4.5.2

**Comment by thinkingserious** [comment] 2016-10-25 20:39
Hi @chumakov-ilya,

Thanks! We agree and I've added this to our backlog for a fix.

**Comment by ottomatic** [comment] 2017-03-22 10:47
I could look into submitting a pull request for this if the library maintainers are interested.

**Comment by thinkingserious** [comment] 2017-03-22 15:55
Hello @ottomatic,

A PR is always welcome :)

We would just need a [signed CLA](https://github.com/sendgrid/sendgrid-csharp/blob/master/CONTRIBUTING.md#cla) to accept it.

Thanks!

With Best Regards,

Elmer

**Comment by jon64digital** [comment] 2017-03-30 12:02
We've been having huge problems with this too. It's completely misleading. It shouldn't even be an HTTP response because it didn't even get that far. It's just a piece of c# code calling another piece of .net code and should get an appropriate exception. If it does have to be an HTTP response then @chumakov-ilya is correct it should be an error code.

**Comment by thinkingserious** [comment] 2017-03-30 16:28
@jon64digital,

Thanks for the feedback, we have added your vote to the issue.

@ottomatic,

Are you still considering a PR? A few days ago we made the CLA process much easier. You no longer need to sign the CLA I linked to previously. When you make your PR, a link will be generated and all you need to do is click the link, fill out a few fields and then sign it by clicking a button.

**Comment by ottomatic** [comment] 2017-03-31 07:34
@thinkingserious ,

Yes, still intending to do this.
I have been busy consuming the SMTP Api instead, since our production servers don't allow outgoing http(s) through the firewall - whereas SMTP on port 587 is allowed.

One thing I would like to do in order to make unit testing easier is to take an HttpClient as an injected dependency in the SendGridAPIClient constructor. This would make it possible to inject a custom RequestHandler into the HttpClient, and in that way take control over the http response. What do you think of this change?

**Comment by SendGridDX** [comment] 2017-03-31 15:02
Hello @ottomatic,

I suggest you add a third constructor that allows for injecting the custom RequestHandler into the HttpClient.

Thanks!

Elmer

**Comment by Jericho** [comment] 2017-03-31 20:21
@ottomatic If you want a "web-proxy-friendly" C# client for the SendGrid API with injectable HttpClient please have a look at StrongGrid (on [github](https://github.com/Jericho/StrongGrid) and on [nuget](https://www.nuget.org/packages/StrongGrid/)).

Also, while we are on the topic of mocking HttpClient calls, whether you decide to use StrongGrid or not I highly recommend you have a look at Richard Szalay's Mockhttp for HttpClient (on [github](https://github.com/richardszalay/mockhttp) and on [nuget](https://www.nuget.org/packages/RichardSzalay.MockHttp/)) which makes mocking HttpClient very easy. I have used it in a few unit testing projects to mock http calls and couldn't be more impressed.

**Comment by SendGridDX** [comment] 2017-03-31 21:12
My apologies @ottomatic,

I was thinking of another SDK. We do have support for Web Proxies in this library: https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/SendGridClient.cs#L45

@Jericho,

Thanks for the suggestions on mocking HttpClient calls, very cool!

**Comment by Jericho** [comment] 2017-03-31 23:42
@SendGridDX the constructor you pointed out does allow injecting `IWebProxy` but not `HttpClient`. Therefore it doesn't allow mocking htpp calls which is what @ottomatic wants to achieve. 

I did a little research and found a [PR](https://github.com/sendgrid/sendgrid-csharp/pull/145) submitted in June 2015 to allow httpclient to be injected but unfortunately it wasn't accepted.

**Comment by SendGridDX** [comment] 2017-04-01 00:25
Thanks @Jericho!

@ottomatic,

Does this point you in the right direction? If you have any further questions, please don't hesitate to reach out.

**Comment by ottomatic** [comment] 2017-04-03 08:28
Yes, the PR which @Jericho  refers to is pretty much what I want to accomplish, and then use that to write a unit test in order to set up the throwing of an exception (e.g. a TimeoutException) when performing the httpclient call. I assume the PR was rejected because it was made against the wrong branch and did not comwe with a signed CLA?

So, the easiest path forward for me is do do both the HttpClient injection and the exception handling (i.e. NOT swallowing the exception) in the same PR. Otherwise I will have to wait for one PR to be approved in order to be able to continue with the issue at hand.

@SendGridDX ,  Is this approach acceptable?

**Comment by SendGridDX** [comment] 2017-04-03 17:33
Thank sounds good @ottomatic, thanks!

**Comment by ottomatic** [comment] 2017-04-04 16:40
Allright. I have cloned the repo, and have successfully gotten started on the development.

**Comment by ottomatic** [comment] 2017-04-11 14:42
Quick update: I am swamped with work. The unit test is ready (and failing), so I should be able to complete the code as soon as I get a few minutes of spare time.

**Comment by benmiller86** [comment] 2017-04-11 15:01
In line with making this library more unit test friendly as @ottomatic has suggested. Would there be any interest in exposing an ISendGridClient etc that the existing classes implement? 

I for one would find it beneficial to be able to easily mock up a SendGridClient for my own unit tests, but cannot because none of the methods are virtual etc.

My preferred mocking library is Moq, but as things stand I have had to go down the road of using Microsofts Fakes to make a ShimSendGridClient just so I can write tests for specific response codes being returned.

**Comment by ottomatic** [comment] 2017-04-11 15:07
@benmiller86 Your suggestion is already formalised in issue #403 and earlier in #201 . I think that would be a good idea and will upvote.

**Comment by ottomatic** [comment] 2017-04-11 16:01
OK, so the pull request has been submitted:
https://github.com/sendgrid/sendgrid-csharp/pull/434

This is my first PR ever!
I think the process so far has been rather painless. Good guidance in the contributing.md document regarding which branch to base the PR on, ow to rebase, etc.

**Comment by thinkingserious** [comment] 2017-04-13 06:42
Hello Everyone,

Thanks to @ottomatic, this issue is resolved in v9.1.1 via PR #434

**Closed by thinkingserious** 2017-04-13 06:42 UTC
Labels: hacktoberfest, status: help wanted, type: bug

**Comment by ottomatic** [comment] 2017-04-13 11:00
Awesome, my pleasure.

**Comment by kirajhpang** [comment] 2017-05-12 01:50
Hello, does this issue fully resolve ?

I am getting this issue after implement our own SendGrid Log.  The `OK` return on production, while in documentation it said only for sandbox test. So we need resend the email to our client. 

![sendgrid error edit](https://cloud.githubusercontent.com/assets/8136063/25978986/573f65e6-36f8-11e7-8e0e-bcab3c531ff1.jpg)

**Comment by thinkingserious** [comment] 2017-05-12 02:58
Hello @Kirajhpang,

I apologize, I don't quite understand the issue. Could you please provide the following details:

1. What are you expecting to happen?
2. Do you have access to the actual status code? (e.g. 202)
3. Can you share the source code?

Thank you!

Elmer

**Comment by ottomatic** [comment] 2017-05-12 07:48
This should have been fixed through the merge of PR #434 as per above. 

@kirajhpang, are you sure you have the latest version of the nuget package? (I have not tried it myself, so I cannot vouch that the new code has made it through the release pipeline).

**Comment by kirajhpang** [comment] 2017-05-12 15:23
@thinkingserious 
Hi, here answer for your question

Actually we facing this issue long time ago, since last time v2 api can't send out email. Some of the emails doesn't reach to `Tos` or `Ccs` or `Bccs`, SendGrid Support also cannot tell particular email did or didn't reach to SendGrid endpoint. Everything is just hanging there. After last major update(current production **v9.1.1**), the status and exception body can be return from SendGrid, we finally can build our own logging module, and found this issue that might be the root cause.  

**1. What are you expecting to happen?**
The email should be send and return as `Accepted` on production, but we capture `Ok` with error message in this case. It happen 1/10 on same type of email we sending out.
After cross check status code documentation on here [Status Codes & Errors](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html) a `Ok` status shouldn't appear in production api endpoint.
After consult SendGrid support, they refer me on this issue track. 

**2. Do you have access to the actual status code? (e.g. 202)**
I no sure what does you mean access to the actual status code.

**3. Can you share the source code?**
As suggestion from @ottomatic, will try **v9.2.0** , if exception still happen, will reach here again. 

Thanks for the effort for building great tool. 😄

**Comment by thinkingserious** [comment] 2017-05-14 16:46
Hi @kirajhpang,

Thanks for the follow up and please let me know how v9.2.0 works for you.

With Best Regards,

Elmer
