### ISSUE TITLE
Email not sent if To address is the same as Bcc address

### ISSUE THREAD

**Issue by davidliang2008** [sendgrid/sendgrid-csharp#451] opened 2017-05-10 22:54 UTC
#### Issue Summary

Email won't go through if the to email address is the same as the Bcc email address. When I change the Bcc email address to something different, the email sending works again.

#### Steps to Reproduce

1. Create the `SendGridClient` with the API key, and create `SendGridMessage`.
2. Set the from address, subject and the email content. Set email template if applied.
3. Set the email to address using `msg.AddTo(new EmailAddress("david.liang@outlook.com"))`.
4. Set the Bcc email list. Here I only add 1 Bcc email: `msg.AddBcc(new EmailAddress("david.liang@outlook.com"));`
5. Try delivering the message using the client: `_client.SendEmailAsync(msg);`

The email won't go through. I also checked the activity log on SendGrid panel. It didn't show any entry. But if I change the Bcc email to something else, the email sending works again, and you will see logs in the activity section.

#### Technical details:

* sendgrid-csharp Version: 9.2.0
* .NETCoreApp 1.1

**Comment by xt0rted** [comment] 2017-05-10 23:22
This is a duplicate of #448

**Comment by thinkingserious** [comment] 2017-05-14 16:52
Hello @davidliang2008,

This is expected behavior, we do not allow duplicate emails. Thanks!

**Closed by thinkingserious** 2017-05-14 16:52 UTC
Labels: status: duplicate
