### ISSUE TITLE
Not Compatible with System.Net.Http 4.3.4

### ISSUE THREAD

**Issue by ricktheartist** [sendgrid/sendgrid-csharp#868] opened 2019-03-05 14:47 UTC
I updated my NuGet Packages included System.Net.Http to the latest version (4.3.4) a few days ago.

Today I discovered a page using the SendGrid package (version 9.10.0) had a failure to load the System.net.Http referenced assembly `Could not load file or assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).`

I later downgraded my System.Net.Http package to version 4.3.3 and then my page worked fine.

**Comment by thinkingserious** [comment] 2019-03-05 19:25
Thanks for the heads up @ricktheartist! I've added this to our backlog.

**Comment by cedemax** [comment] 2019-03-17 08:48
I have the same error message, but the workaround proposed by @ricktheartist does not solve it for me. I started getting this error message when i updated from net46 to net472.

**Comment by jnyrup** [comment] 2019-04-18 21:15
@ricktheartist What framework are you targeting?
If you're targeting .Net Framework 4.x, SendGrid 9.11 has an unnecessary *package* dependency on `System.Net.Http`.
That could cause the problem as .Net Framework itself includes `System.Net.Http`.
If you haven't tried already, try add an assembly reference to `System.Net.Http`.

**Comment by bmeredith** [comment] 2019-05-15 21:34
Any update on this? 

We would really like to use the dynamic template functionality in >= 9.10, but are currently blocked because of the `System.Net.Http` dependency.

**Comment by thinkingserious** [comment] 2019-05-21 01:58
Hi @bmeredith,

I believe this is a duplicate of [this issue](https://github.com/sendgrid/sendgrid-csharp/issues/742) which has an associated PR [here](https://github.com/sendgrid/sendgrid-csharp/pull/743). Could you please upvote both to help increase its value in our backlog? Thank you! 

With Best Regards,

Elmer

**Comment by thinkingserious** [comment] 2019-05-21 01:59
Please follow and vote on this PR: https://github.com/sendgrid/sendgrid-csharp/pull/743

Thanks!

**Closed by thinkingserious** 2019-05-21 01:59 UTC
Labels: status: duplicate

**Comment by luylucas10** [comment] 2019-07-17 19:53
I solved this commenting the entry in the app.config and web.config files:
```
<!--<dependentAssembly>
    <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-4.1.1.3" newVersion="4.1.1.3" />
</dependentAssembly>-->
```
I updated to last version of these packages, did the comment, now it works.

**Comment by umartopia** [comment] 2020-10-27 12:00
I tried out various solutions (removing the dependentAssembly OR specifying the binding redirect as well). None of them worked.

However, the only solution which worked for me was to explicitly set Specific Version for System.Net.Http (or whatever DLL giving you version issues) to False from Visual Studio.

https://files.slack.com/files-pri/T11NXDZ4G-F01DDPMG1FC/image.png
