### ISSUE TITLE
Support System.Text.Json

### ISSUE THREAD

**Issue by alanwales** [sendgrid/sendgrid-csharp#1050] opened 2020-09-28 15:03 UTC
With the introduction of .Net 5 next month it is clear that Newtonsoft is strongly discouraged for use in modern .Net applications. We have noticed memory pressure occurring because the SendGrid client is still based on Newtonsoft json serialization and cannot be changed. It would be great to be able to swap out the serializer for the new System.Text.Json library

**Comment by thinkingserious** [comment] 2020-09-28 21:48
Hello @alanwales,

Thanks for taking the time to report this! I'm marking this as duplicate of #985. Please vote on that issue and/or add a comment to help it gain priority.

With best regards,

Elmer

**Closed** 2020-09-29 00:03 UTC
Labels: status: duplicate
