### ISSUE TITLE
Email Activity API Unique Arguments Filter

### ISSUE THREAD

**Issue by isiahpasquale** [sendgrid/sendgrid-csharp#694] opened 2018-05-15 22:07 UTC
#### Issue Summary

Attempting to filter by the unique_args query type is throwing an error about incompatible comparison usage:
`"operator = is incompatible with MAP<STRING,STRING>, STRING"`

The documentation for the call asks for it to be formatted like so 
`unique_args="example argument"`

I have tried passing every variation of just the key, just the value, or a full key-value pair object but no matter how it's passed it treats it as a string and throws that error.  I've tried it both via the latest sendgrid-csharp and via the try it yourself on the API documenation page.  This is especially confusing since the API doc leaves the example as simple as "example argument" which leads me to believe it should be possible to filter by just a key or value.

#### Steps to Reproduce

Here is the code snippet i've used.  
My custom arguments added to some messages before send:
```               
msg.CustomArgs = new Dictionary<string, string>()
{
    {"basic_message_id", Guid.NewGuid().ToString()}
};
```
And how i'm attempting to search for them afterwards:
```
var queryParams= @"{
    'query': 'unique_args=""basic_message_id""',
    'limit': 5
var response = await _sendGridClient.RequestAsync(
                method: SendGridClient.Method.GET,
                urlPath: "messages",
                queryParams: queryParams)
                .ConfigureAwait(false);
```
Result: `"operator = is incompatible with MAP<STRING,STRING>, STRING"`
FYI - I've tried passing just the key and just the value and also attempted to pass in a dictionary type along the lines of so:
`"{'basic_message_id','value'}"`  (as well as every variation i could think of trying)

Any assistance would be greatly appreciated.

#### Technical details:

* sendgrid-csharp Version: 9.8.0.0
* Platform ASP.NET
* .NET Version: 4.5.2

**Comment by Jericho** [comment] 2018-05-22 22:46
I confirm that I am also seeing the `operator = is incompatible with MAP<STRING,STRING>, STRING` exception when attempting to query email activities and setting a filter on a custom argument.

**Comment by Jericho** [comment] 2018-05-22 22:54
By the way, I was able to reproduce this issue using [StrongGrid](https://github.com/Jericho/StrongGrid) and also using the live API docs as you suggested:

![image](https://user-images.githubusercontent.com/112710/40394460-8e370c18-5df1-11e8-8260-356c7929ad9d.png)

**Comment by thinkingserious** [comment] 2018-06-08 21:28
Hi @isiahpasquale and @Jericho,

It looks like we need to update the docs and examples. 

The queries should be formed like this:

`/v3/messages?limit=10&query=(unique_args['name']="Joe")`
`/v3/messages?limit=10&query=(unique_args['name'] like "Joe")`

for example.

Leaving this open and adding to our backlog for a fix.

With Best Regards,

Elmer

**Comment by Jericho** [comment] 2018-06-12 18:44
I confirm that filtering on `unique_args` using the updated format works as expected. I published a new release of the [StrongGrid](https://www.nuget.org/packages/StrongGrid/) nuget package with changes that allow to search email activities with "unique_args" filters.

**Comment by isiahpasquale** [comment] 2018-06-12 20:31
Worked great for me as well.
Thanks for the response.

**Comment by himanshuphirke** [comment] 2019-02-11 13:33
> Hi @isiahpasquale and @Jericho,
> 
> It looks like we need to update the docs and examples.
> 
> The queries should be formed like this:
> 
> `/v3/messages?limit=10&query=(unique_args['name']="Joe")`
> `/v3/messages?limit=10&query=(unique_args['name'] like "Joe")`
> 
> for example.
> 
> Leaving this open and adding to our backlog for a fix.
> 
> With Best Regards,
> 
> Elmer

Could you please provide an example of IN operator also?
I am trying to locate email status based on multiple unique args and have all in one email call so that less network latency

**Comment by dkirsanov** [comment] 2020-04-29 12:10
> Could you please provide an example of IN operator also?
> I am trying to locate email status based on multiple unique args and have all in one API call so that there is less network latency

@himanshuphirke , 
`const queryParams = {
    'limit': 10,
    'query': `(unique_args['id'] IN ("2", "3"))`
  };`
It was a quest for me as well :)

**Comment by eshanholtz** [comment] 2020-09-02 00:01
Closing as this in a non-library issue.

**Closed by eshanholtz** 2020-09-02 00:01 UTC
Labels: difficulty: unknown or n/a, type: non-library issue

**Comment by Andrii-Smoliak** [comment] 2021-07-28 13:47
Is it possible to include custom arguments to response?
