### ISSUE TITLE
NuGet NU1108 cycle detected error (9.24.0)

### ISSUE THREAD

**Issue by jmullis** [sendgrid/sendgrid-csharp#1121] opened 2021-07-02 20:04 UTC
Visual Studio 2019 v16.9.3 gives a "NuGet NU1108: cycle detected" error when attempting to add the current (9.24.0) package. This is the first time adding this package; the project is brand new. This is my first experience adding the SendGrid package, but have used NuGet packages for many years. This is the first time I've ever seen this type of error.

![image](https://user-images.githubusercontent.com/761007/124323117-c260fc00-db4e-11eb-858d-47d6010db46c.png)

Thanks for your help.

**Comment by JenniferMah** [comment] 2021-07-06 19:30
Hi @jmullis I'm not able to reproduce this error. Are you able to install any of the other versions of the SendGrid package ([9.23.2](https://www.nuget.org/packages/SendGrid/9.23.2) or [9.23.1](https://www.nuget.org/packages/SendGrid/9.23.1))? Is it possible that your project is named SendGrid? Sometimes this error will occur when a project and a package have the same name.

**Comment by jmullis** [comment] 2021-07-06 20:00
Hi Jennifer,

My project is indeed named SendGrid! I'm out of the office for about 30
mins but will try when i return.

Thanks for the quick response.

-Jim

**Comment by akunzai** [comment] 2021-07-06 20:03
Duplicated with #1114

**Comment by shwetha-manvinkurke** [comment] 2021-07-13 15:11
@jmullis do you still need help?

**Comment by akunzai** [comment] 2021-07-26 11:05
Hi @jmullis , you should close this issue if your problem is solved.

**Comment by jmullis-enzo** [comment] 2021-07-26 17:14
The main project class was indeed named SendGrid. We changed it to SendGridApi and had no further problem adding the NuGet package.

Problem solved.

**Closed** 2021-07-26 17:19 UTC
Labels: status: waiting for feedback, type: getting started
