### ISSUE TITLE
Client Throws 'Error while copying content to a stream' on 401 API Response

### ISSUE THREAD

**Issue by oatsoda** [sendgrid/sendgrid-csharp#648] opened 2017-12-20 14:55 UTC
When making a call to `SendGridClient.SendEmailAsync` using a deliberately invalid API Key, rather than receiving a `Response` with a `StatusCode` of 401 Unauthorized, an exception is thrown:

    System.Net.Http.HttpRequestException occurred
      HResult=0x80131620
      Message=Error while copying content to a stream.
      Source=<Cannot evaluate the exception source>
      StackTrace:
       at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__49.MoveNext()
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at SendGrid.SendGridClient.<MakeRequest>d__23.MoveNext()
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at SendGrid.SendGridClient.<RequestAsync>d__24.MoveNext()
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at SendGrid.SendGridClient.<SendEmailAsync>d__25.MoveNext()

#### Technical details:

* sendgrid-csharp Version: 9.9.0
* Azure Function running Net462

Looking at the data received from SendGrid, this may or may not be due to the fact that the `Content-Length` header is > 0 but there is no response content:

![image](https://user-images.githubusercontent.com/3919587/34212922-b58b5320-e595-11e7-80ce-862b46f716aa.png)

**Comment by oatsoda** [comment] 2017-12-20 16:10
Upon further investigation it appears that if the original context-length I am POSTing exceeds 2063 characters then I get the response with no content.

If the original content-length < 2064 then I get the correct response:

    {
        "errors": [
            {
                "message": "The provided authorization grant is invalid, expired, or revoked",
                "field": null,
                "help": null
            }
        ]
    }

**Comment by oatsoda** [comment] 2017-12-20 16:13
Upon further investigation it appears that this is somehow linked to the original content-length of the POST request.

If the original content is small (i.e. less in the email body) then I get the correct response content:

    {
        "errors": [
            {
                "message": "The provided authorization grant is invalid, expired, or revoked",
                "field": null,
                "help": null
            }
        ]
    }

**Comment by thinkingserious** [comment] 2017-12-20 21:33
Hi @oatsoda,

That's an interesting bug, thanks for sharing it with us!

I've added this to our backlog for further investigation.

With Best Regards,

Elmer

**Comment by oatsoda** [comment] 2017-12-21 08:10
@thinkingserious Thanks. I have also opened a support ticket with SendGrid directly as it may be an API issue rather than a client issue. I will update here once I receive a response.

**Comment by oatsoda** [comment] 2017-12-22 15:04
[Source.zip](https://github.com/sendgrid/sendgrid-csharp/files/1582792/Source.zip)
[SendGridTest.zip](https://github.com/sendgrid/sendgrid-csharp/files/1582794/SendGridTest.zip)

Attached are Source and Binaries of a test app demonstrating the failure.  I really suspect this is an API issue rather than a SendGridClient issue, but updating it here anyway.

Run the app with a value to repeat the lines in the email body.  Once you exceed 56 it gets the exception. Tested on multiple machines and also from an Azure VM.

**Comment by oatsoda** [comment] 2018-01-02 08:02
@thinkingserious SendGrid Support have sent me your way :)

> It looks like you've been working with one of our Engineers via the github repository. He is definitely your best resource for this particular issue. This bug falls a bit outside of the scope of Support, but regardless of whether it's client related or API related, the engineer you were in contact with via GitHub should be able to assist.

Any ideas on what the issue could be? Can you reproduce it using my test app?

**Comment by thinkingserious** [comment] 2018-01-02 19:04
Hello @oatsoda,

Thank you for the updated information. This issue is still working its way up our backlog.

In the mean time, you may want to [try the API call directly](https://sendgrid.com/docs/API_Reference/api_v3.html) to officially rule out the client as the culprit.

**Comment by oatsoda** [comment] 2018-01-03 08:35
Hi @thinkingserious 

Yes, I can reproduce it directly to the API in Postman too. However, I sent SendGrid Support the sample Postman call and it didn't reproduce for them!  I suspect this *is* API related rather than client related. The API just doesn't return any content if the original request is above a certain size.  I'd be really interested to know if the sample app reproduces it for you - I have tried on multiple machines in multiple geographic locations and it reproduces it each time.  Quite why it didn't work via Postman for SendGrid Support I don' know - perhaps a network issue which isn't occurring inside the SendGrid network?  (I vaguely remember coming across something similar years ago regarding MTU sizes on network devices and responses being split over multiple packets being lost - but I think that is clutching at straws!)

**Comment by Jericho** [comment] 2018-01-03 18:03
I can confirm some of the observations that @oatsoda made regarding this issue. Please note that I used [StrongGrid](https://github.com/Jericho/StrongGrid) instead of SendGrid's C# client in order help determine if this issue is specific to the client or not:

_Observation 1:_
Using the same email content included in @oatsoda's sample code (including the large text and HTML content), I observed that the response from SendGrid's API is `HTTP/1.1 401 Unauthorized` (this is expected since the sample code is intentionally using a bogus api key). I also observe that the content of the response is empty. Finally, I observe that the response contains the following header: `Content-Length: 116` which is contradictory with the fact that the response content is empty. This points to a server-side issue.

_Observation 2:_
Using the email content included in @oatsoda's  sample code with much smaller text and HTML content, I observed that  the response from SendGrid's API is `HTTP/1.1 401 Unauthorized` and the content of the response is `{"errors":[{"message":"The provided authorization grant is invalid, expired, or revoked","field":null,"help":null}]}` which is 116 characters long and is consistent with the  `Content-Length: 116` header that I also observe in this scenario.

_Observation 3:_
I am unable to reproduce the `Error while copying content to a stream` exception that @oatsoda experienced when the response is empty. Since the only difference between my setup and his is that I am using an alternate C# client, this leads me to conclude that this issue is specific to SendGrid's C# client.

_Conclusion:_ 
There seems to be two distinct issues: 
1. The server is not returning the expected content with the response in the scenario described in _observation 1_ (combined with the fact that it returns incorrect `Content-Length`)
2. The client is not properly handling situations where the body of the response is empty and/or relying on the incorrect `Content-Length` to determine if the body of the response contains any content.

**Comment by oatsoda** [comment] 2018-01-04 09:10
Thanks @Jericho for confirming!

Strange that the error doesn't occur in other clients. The stack trace indicates that it is an error in `HttpClient.FinishSendAsyncBuffered` - but I suppose it could be that other clients may not use this...

**Comment by oatsoda** [comment] 2018-02-11 09:59
@thinkingserious Any confirmation of an API problem regarding the empty response? Causing me quite a lot of grief as authentication failures not being detected.

I suspect the secondary issue regarding the client side exception is actually just net core http client expecting responses to be well formed - hence relying on content-length.

**Comment by thinkingserious** [comment] 2018-02-14 20:41
@oatsoda,

I can check on that for you. What's the support ticket number?

**Comment by oatsoda** [comment] 2018-02-16 11:10
The number *was* #1331298, but it is closed because they replied with:

> It looks like you've been working with one of our Engineers via the github repository. He is definitely your best resource for this particular issue. This bug falls a bit outside of the scope of Support, but regardless of whether it's client related or API related, the engineer you were in contact with via GitHub should be able to assist.

Hence I am asking you for an update :)

**Comment by thinkingserious** [comment] 2018-02-17 17:55
Ah thanks @oatsoda,

It looks like there are 2 issues here as Jericho has illustrated. Issue #2 is something I can attempt to fix and so I'll leave this open for a fix. For issue #1, I'll ping the relevant engineering team to see if it's on deck for a fix.

Our backlog is pretty full at the moment, so in order for this to gain some priority, additional +1's or a PR helps greatly.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment] 2018-04-05 18:06
@oatsoda,

There is an internal bug happening here where the API is not returning the correct content-length. I'm going to circle back with product and engineering to see where we are on a fix. Thanks!

**Comment by janus007** [comment] 2018-04-17 18:02
I've had the same error after moving a website to Azure. 

I fixed it by changing SendGridClient.cs, MakeRequest method.

Instead of:

```
Line 250: 
HttpResponseMessage response = await client.SendAsync(request, cancellationToken).ConfigureAwait(false);
```

to

`HttpResponseMessage response = await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);`

**Comment by thinkingserious** [comment] 2018-04-18 01:34
Hi @janus007,

Thanks for sharing this solution, you are awesome! I will look into it and see if I can confirm the solution. 

With Best Regards,

Elmer

**Comment by thinkingserious** [comment] 2018-06-27 00:19
Not yet @DanielStout5, but I appreciate you taking the time to add a comment. 

Each +1/comment adds priority to issues in our backlog.

**Comment by APErebus** [comment] 2018-11-21 04:14
Just thought I'd chime in and say I ran into this issue today as well.

The underlying issue was that our sub-user (this was on a testing account), had run out of daily credits When I added some credits on that account, the error went away.

**Comment by AmbroiseCouissin** [comment] 2018-11-28 17:41
I ran into the same issue and I'm not sure what to do. It works under windows but not under linux alpine:
```
System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.CopyToExactLengthAsync(Stream destination, UInt64 length, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at SendGrid.SendGridClient.MakeRequest(HttpRequestMessage request, CancellationToken cancellationToken)
   at SendGrid.SendGridClient.RequestAsync(Method method, String requestBody, String queryParams, String urlPath, CancellationToken cancellationToken)
   at SendGrid.SendGridClient.SendEmailAsync(SendGridMessage msg, CancellationToken cancellationToken)
```

**Comment by AmbroiseCouissin** [comment] 2018-11-29 07:39
Finally found out why. When we send an html content that is quite big and that an error comes back, this error happens instead of `Unauthorized` let's say. Our issue was the following: "{\"errors\":[{\"message\":\"Maximum credits exceeded\",\"field\":null,\"help\":null}]}"

**Comment by danielcongrove** [comment] 2018-12-21 16:44
+1, started running into this issue as well.

**Comment by somoreingold** [comment] 2019-01-23 17:15
+1 Same here.

**Comment by adamseebeck** [comment] 2019-01-28 14:02
Same problem. Mine will work locally but when I push to azure it stops working.

**Comment by bioyeneye** [comment] 2019-01-29 16:37
@somoreingold were you able to resolve the issue?

**Comment by S1r-Lanzelot** [comment] 2019-02-22 20:31
+1 same stacktrace @AmbroiseCouissin

**Comment by w3bStuff** [comment] 2019-04-22 15:16
Problem still happening when the API key is invalid.
The API v2 used to return 400, not ideal as it should return 401 but still better than:
"Error while copying content to a stream." and "Unable to read data from the transport connection: The connection was closed".
Any timeline for resolution after nearly 1.5 year?

**Comment by jinsaini** [comment] 2019-05-30 09:23
Any fix on this, randomly started happening on our live system too since 26th May, no code was changed.

**Comment by thinkingserious** [comment] 2019-06-03 19:42
Hello Everyone,

While I can't give a specific timeline, I can say that all of your upvotes and comments have caused this issue to continue to rise in our backlog. I'm hopeful we can knock this one out soon.

Thanks for taking the time to create a comment or upvote!

With Best Regards,

Elmer

**Comment by BlackstarSolar** [comment] 2019-06-13 08:05
+1 same here

**Comment by jinsaini** [comment] 2019-06-13 08:52
> @thinkingserious Any fix on this, randomly started happening on our live system too since 26th May, no code was changed.
> 
> Getting the Unauth response if text email sent (key is correct) and getting 'Error while copying content to a stream' if HTML email is used.
> 
> at SendGrid.SendGridClient.d__23.MoveNext() in C:\Users\ethomas\Documents\GitHub\sendgrid-csharp\src\SendGrid\SendGridClient.cs:line 250
> 
> SendGrid ticket no. Request #2238173

Our issue turned out to be that we had used our monthly allowance and needed to increase it. Would be nice to actually get the correct error msg back

**Comment by thinkingserious** [comment] 2019-06-14 04:08
Thanks for reporting back here @jinsaini! Indeed, that error is very cryptic and non-helpful. I'm leaving this issue open for further investigation.

**Comment by Jordank321** [comment] 2019-06-26 20:16
Hello, in a live system we have one particular email for a single event that causes this (even on retry) but it if fine for other email of the same type. This is very confusing for us.

**Comment by thinkingserious** [comment] 2019-06-28 16:57
Hello @Jordank321,

When you say "email of the same type", do you mean an email that is going to the same domain? You might want to check out your [Email Activity logs](https://app.sendgrid.com/email_activity) to further debug.

With best regards,

Elmer

**Comment by DustinReagan** [comment] 2019-07-05 14:11
I'm running into the same problem.  

For me, it only happens when I run my .net core app in Docker.  Works fine when running in dev mode from visual studio.

**Comment by tedvanderveen** [comment] 2019-07-17 19:29
We suffer from the same bug, please fix...

**Comment by contactsamie** [comment] 2019-07-23 08:04
> +1 same stacktrace @AmbroiseCouissin
> 
> We ended up using just straight SMTP due the reliability issues of this library.

would you like to share your solution?

**Comment by sebandres** [comment] 2019-08-18 12:35
> > +1 same stacktrace @AmbroiseCouissin
> > We ended up using just straight SMTP due the reliability issues of this library.
> 
> would you like to share your solution?

@contactsamie I believe he means this: https://sendgrid.com/docs/for-developers/sending-email/getting-started-smtp/

**Comment by sebandres** [comment] 2019-08-18 12:37
I also got here due to this cryptic error and in my case it turned out to be a missing variable for the Api Key in the CI/CD pipeline that resulted into the same message when trying to send an email without an ApiKey.

**Comment by crowbarsolutions** [comment] 2019-10-15 21:27
Getting this intermittently as well, our application is configured to retry failed requests. We have noticed that in cases where this error gets thrown, and an identical request is attempted immediately after the failure, the request will work properly. Everything on the client side remains the same, it's just the response from the server that is the culprit.

**Comment by jwisener** [comment] 2019-10-16 03:30
@thinkingserious Geeze, 2 years and it's clearly a bug. So are you saying that in order to work on a "bug" you treat it like "new functionality". I wish we could do that. When there is a production bug, we make a priority to hotfix it as soon as possible.

**Comment by andre-castro-garcia** [comment] 2019-11-07 19:54
I had exact same error when running my application with invalid public IP inside an AKS cluster (inside a docker container obviously).

To fix this issue I needed:
1. Add a static public IP in my AKS cluster (https://docs.microsoft.com/azure/aks/egress);
2. Add this public IP in Sendgrid IP whitelist;

Now everything works!!!!!!! 😄

**Comment by dhtatsch** [comment] 2019-11-14 11:27
We have the same problem with our azure application here. We opened a support call, but they say it's a "connection" issue.

**Comment by tedvanderveen** [comment] 2019-11-14 13:29
Just like @janus007 reported before, the issue arises when sending a request that is big and chopped into chunks over the wire and miss out any important response status codes/headers. You can fix it like this:
https://github.com/tedvanderveen/sendgrid-csharp/commit/eb100f35a4bacdae062117c0ca526ad5d55cff9f
See also https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httpcompletionoption#fields

**Comment by oznurco** [comment] 2019-12-27 19:15
I use sendgrid v9.12.0 in live application and I have the same problem. I can see that the problem is too old, have you any ideat about that presumably when the problem will be solved?

**Comment by lurumad** [comment] 2020-01-09 08:57
Hi @oznurco 

Same error for me in Azure Function v3 even in local.

Regards!

**Comment by oznurco** [comment] 2020-01-10 13:06
Hi @lurumad . I solved my problem. SendGrid keys were wrong in the production environment.

**Comment by chriswill** [comment] 2020-06-17 18:25
This is really sad that this error so obscures the actual error.

My html body is only 6349 bytes.  Only when I turned off the html body entirely did I get to see the actual error, which was:

`{"errors":[{"message":"The requestor's IP Address is not whitelisted","field":null,"help":null}]}`

I had to chase through non-relevant logs for hours for what should have been a simple fix.

**Comment by AndreduToit** [comment] 2020-08-28 07:45
I also experienced the "Error while copying content to a stream." exception on incorrect key. Not a big issue to handle it but the exception is not really helpful. Still the same bug after what looks like about 32 months - not good.

**Comment by childish-sambino** [comment] 2020-08-28 15:30
Similar to https://github.com/sendgrid/sendgrid-java/issues/259 and https://github.com/sendgrid/sendgrid-java/issues/641

Closing this as a non-library issue since it cannot/should not be remedied in client-side code. I've opened an internal ticket for tracking (reference ID: _CL-2667_). Please reference that ticket when contacting support regarding this issue.

Note that support and backend product teams do not use GitHub to prioritize work. Contacting [support](https://support.sendgrid.com/hc/en-us) is the best way to push this issue along.

**Closed by childish-sambino** 2020-08-28 15:30 UTC
Labels: difficulty: medium, status: work in progress, type: bug

**Comment by oatsoda** [comment] 2020-09-02 08:55
@childish-sambino 

- There was already an [support request](https://github.com/sendgrid/sendgrid-csharp/issues/648#issuecomment-366207789) for this.

- If you see this [post](https://github.com/sendgrid/sendgrid-csharp/issues/648#issuecomment-355081908), there is technically a weakness in the library too.

**Comment by childish-sambino** [comment] 2020-09-02 15:18
@oatsoda This is something the needs to be handled via support so I recommend opening a new ticket there. The engineers that manage these libraries do not handle backend issues and support is the path forward.

For the item related to this library handling _invalid_ API responses, I'm not convinced this library should be doing something different. It would basically be just failing in a different way. If the backend issue is resolved and a proper response is returned then there would be no special error handling here.

**Comment by AndreduToit** [comment] 2020-09-02 15:27
Oh, I see but disagree. Getting a response of  'Error while copying content to a stream' when the failure is an invalid API – well this response does not help any developer.

**Comment by AndreduToit** [comment] 2020-09-03 02:10
Oh, I see but respectfully disagree. Getting a response of  'Error while copying content to a stream' when the failure is an invalid API – well this response does not help any developer. The one thing that the library may do differently is to provide a response which would aid sendgrid developer customers to track down their mistakes more efficiently. Maybe something along the lines of  "Error - API key ......"?

**Comment by childish-sambino** [comment] 2020-09-04 15:19
We use the standard [HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient) which is where the exception emanates from. Adding logic/handling for issues where the response is not valid (e.g., content length header does not match actual content length) is better suited there. I suspect the reason this was not seen in the other repo is because of the [
Pathoschild/FluentHttpClient](https://github.com/Pathoschild/FluentHttpClient) client wrapper.

Still, given that this is an API-level bug that affects multiple libraries/languages, I don't see creating workarounds in multiple places a viable solution for handling API bugs regarding large payloads and bad API keys.

**Comment by joanna1010** [comment] 2020-11-18 20:45
I can't believe this is still an issue after 3 years, and there's no clear documentation on how to fix this one.
We are a paid customer, and the PO has escalated to suggest switching the integration. 
Also if you can't support/maintain your API, please do not open one. just waste people's time and money.

**Comment by joanna1010** [comment] 2020-11-26 20:39
HI we have submitted a support ticket and they asked us to open a github issue here.
Would you please unify your response?


> @oatsoda This is something the needs to be handled via support so I recommend opening a new ticket there. The engineers that manage these libraries do not handle backend issues and support is the path forward.
> 
> For the item related to this library handling _invalid_ API responses, I'm not convinced this library should be doing something different. It would basically be just failing in a different way. If the backend issue is resolved and a proper response is returned then there would be no special error handling here.

![image](https://user-images.githubusercontent.com/5986383/100390206-6dc74100-3094-11eb-9dba-55f958050b32.png)

**Comment by nmg196** [comment] 2021-01-20 12:31
Still getting this problem in 2021.  I don't understand why the client cannot correctly process the result and expose the real error rather than just throwing an obscure exception.  I can see in Postman that a perfectly valid 401 Unauthorised response comes back (due to non whitelisted IP), except instead of just setting IsSuccessStatusCode to false it throws an unhelpful exception.
