### ISSUE TITLE
System.IO.FileLoadException Crashes Web App

### ISSUE THREAD

**Issue by ubar-on** [sendgrid/sendgrid-csharp#493] opened 2017-07-13 10:37 UTC
#### Issue Summary

ASP.NET WebApi application. Targets .NET 4.6.2. SendGrid version 9.4.1, System.Net.Http version 4.3.2. 

When I try to send an email using SendEmailAsync(), the process crashes with the event log message below. It says could not load System.Net.Http 4.1.1.1, but that is not the version I'm using. 

I've reviewed threads with similar problems, but they mention System.Net.Http 4.3.1 and up as the solution. I have this. Any ideas appreciated.

Thanks
Udi

Event Log:
========================
An unhandled exception occurred and the process was terminated.

Application ID: /LM/W3SVC/6/ROOT

Process ID: 6696

Exception: System.IO.FileLoadException

Message: Could not load file or assembly 'System.Net.Http, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

StackTrace:    at MedMinder.Common.EmailSender.SendEmails()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
========================

**Comment by thinkingserious** [comment] 2017-07-13 23:25
Hi @ubar-on,

I believe this is a duplicate of [this issue](https://github.com/sendgrid/sendgrid-csharp/issues/442). Please follow that issue for progress and I'll add your vote to help it gain priority in our backlog, thanks!

With Best Regards,

Elmer

**Closed by thinkingserious** 2017-07-13 23:25 UTC
Labels: status: duplicate
