### ISSUE TITLE
{"Unknown element: html"}

### ISSUE THREAD

**Issue by duongthaiha** [sendgrid/sendgrid-csharp#126] opened 2015-04-24 13:27 UTC
Just updated to Send Grid C# to 6.0.0 and got this error  {"Unknown element: html"}
Here is the sample of code. Can you please have a look? Thank you very much

  
                SendGridMessage myMessage = new SendGridMessage();
                if (string.IsNullOrEmpty(email)) email = "xxxx";
                myMessage.AddTo(email);
                Console.WriteLine("Sending Email {0}",email);
                myMessage.From = new MailAddress("xxx", "xxx");
                myMessage.Subject = "Connection Test Log";
                myMessage.Text = "Check log file";
                var logfiles = Directory.GetFiles(Directory.GetCurrentDirectory(), "*.log");
                foreach (var file in logfiles)
                {
                    myMessage.AddAttachment(file);
                }

                var username = ConfigurationManager.AppSettings["SendGrid:Username"];
                var pswd = ConfigurationManager.AppSettings["SendGrid:Password"];

                var credentials = new NetworkCredential(username, pswd);

                var transportWeb = new Web(credentials);

                 transportWeb.DeliverAsync(myMessage).Wait();

**Comment by brandonmwest** [comment] 2015-04-24 13:29
Thanks for the bug report, I will look into it

**Comment by artmetz** [comment] 2015-04-24 13:47
I am also having the same issue with the upgrade to 6.0.
SendGridMessage cMessage = new SendGridMessage();
cMessage.DisableClickTracking();

cMessage.From = new MailAddress("xxxx");

List<string> recipients = new List<string>
{
    @"Art Metz <xxxx>"
};

cMessage.AddTo(recipients);

cMessage.Subject = "Testing the SendGridMessage";

cMessage.Html = "<p>html test</p>";
cMessage.Text = "plain text test";

MemoryStream stream = new MemoryStream(System.Text.Encoding.UTF8.GetBytes("1,2,3"));
cMessage.AddAttachment(stream, "testutf.csv");
stream = new MemoryStream(System.Text.Encoding.ASCII.GetBytes("1,2,3"));
cMessage.AddAttachment(stream, "testascii.csv");

var username = "azure_xxx@azure.com";
var pswd = "xxx";
NetworkCredential credentials = new NetworkCredential(username, pswd);
 
var transportWeb = new Web(credentials);

transportWeb.DeliverAsync(cMessage).ConfigureAwait(false).GetAwaiter().GetResult();

**Comment by brandonmwest** [comment] 2015-04-24 14:13
I've found the bug. Silly mistake caused by a bad merge. Fix coming shortly.

**Comment by brandonmwest** [comment] 2015-04-24 14:20
Please try 6.0.1 and sorry for the trouble.

**Comment by bsimser** [comment] 2015-06-11 03:52
Updated to 6.0.1 and found this error is back when you're trying to run from localhost through an authenticated proxy (at least that's what my setup was). Once I was off the network and using a regular network connection the error was gone. I'm assuming I can set/pass a proxy object in the credentials (I can't remember where the proxy fits in) so I can test this in the morning when I'm back on the network to confirm you can do it behind an authenticated proxy.

**Comment by zzzcochrane** [comment] 2015-06-30 02:16
I am on 6.1.0 and  had to throw in the last line for it to work and not throw null issue.            
transportWeb.DeliverAsync(myMessage);
//2.3 seconds to avoid issue of above method returning null
 System.Threading.Thread.Sleep(2300);

**Comment by Gaz79** [comment] 2015-07-15 18:17
Hi, I am also on 6.1.0 and found the "Unknown element: html" bug is back.
The version and code has been running stable for about 2 months and the only change was my azure subscription which I upgraded and it automatically deleted my old sendgrid account so I had to create a new sendgrid account and api key.

**Comment by WiredSoftware** [comment] 2015-08-05 11:12
This issue seems to have come back today - was working fine up until now. I've been using version:

<package id="Sendgrid" version="6.1.0" targetFramework="net45" />
<package id="SendGrid.SmtpApi" version="1.3.1" targetFramework="net45" />

I've changed nothing, it was working fine yesterday...

**Comment by ohadschn** [comment] 2015-10-15 13:08
I am on 6.1.0.0 and recently started getting these, any ideas?

**Comment by csantero** [comment] 2015-10-16 20:28
Since yesterday I have been experiencing the same problem as @ohadschn. The SendGrid endpoint has started returning 406 Not Acceptable errors along with a document body consisting of plain HTML, which is not expected by this library. So the real problem isn't with sendgrid-csharp, but with the SendGrid server.

Interestingly enough this problem only seems to happen for my app hosted on Azure. When developing in VS locally it works as expected...

**Comment by ohadschn** [comment] 2015-10-22 18:59
@csantero I'm curious, how did you examine the Sendgrid HTTP response if it only happened on your Azure app? Have you used the REST API directly?

**Comment by csantero** [comment] 2015-10-22 19:30
@ohadschn I modified the Web transform to attach a logger in the HttpClient:

```
	    public Web(string apiKey, NetworkCredential credentials, TimeSpan httpTimeout)
	    {
            ...
            _client = new HttpClient(new LoggingHandler(new HttpClientHandler()));
            ...
	    }
        public class LoggingHandler : DelegatingHandler
        {
            public LoggingHandler(HttpMessageHandler innerHandler)
                : base(innerHandler)
            {
            }

            protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            {
                Debug.WriteLine("Request:");
                Debug.WriteLine(request.ToString());
                if (request.Content != null)
                {
                    Debug.WriteLine(await request.Content.ReadAsStringAsync());
                }
                Debug.WriteLine("");

                HttpResponseMessage response = await base.SendAsync(request, cancellationToken);

                Debug.WriteLine("Response:");
                Debug.WriteLine(response.ToString());
                if (response.Content != null)
                {
                    Debug.WriteLine(await response.Content.ReadAsStringAsync());
                }
                Debug.WriteLine("");

                return response;
            }
        }
```

**Comment by ohadschn** [comment] 2015-10-22 19:35
@csantero oh so you rebuilt sendgrid-sharp?

**Comment by JManis** [comment] 2015-11-12 15:01
We have recently begun having the exact problem @ohadschn and @csantero describe: Azure site, no code changed, now fails Deliver every time with same symptoms.

**Comment by Polymetrika** [comment] 2015-11-26 02:19
Same issue as others: Azure sites are the only issues, with the same symptoms. I am developing with SendGrid 6.3.0 from the Nuget package.

**Comment by brandonmwest** [comment] 2015-12-02 21:18
This should be fixed now. It was an API-level issue affecting Azure users only. Please let me know if anyone continues to experience the problem.

**Closed by brandonmwest** 2015-12-02 21:18 UTC

**Comment by JManis** [comment] 2015-12-02 23:13
I've just confirmed that it is now working for us again. Thanks for looking into the problem.

**Comment by azharuddinsayed** [comment] 2017-09-07 07:23
Still i am getting the same issue

**Comment by thinkingserious** [comment] 2017-09-07 16:14
Hello @azharuddinsayed,

What version of the library are you using and on what platform is this happening?

Thanks!

With Best Regards,

Elmer
