### ISSUE TITLE
Unable to leave "To" filed blank if "CC" is filled.

### ISSUE THREAD

**Issue by gill1986** [sendgrid/sendgrid-csharp#1096] opened 2021-03-22 04:49 UTC
Hi,

SendGrid 9.22.0

var msg = MailHelper.CreateSingleEmail(from, to, subject, string.Empty, htmlContent);
msg.AddCc(new EmailAddress("test@gmail.com"));

If I am leaving "To" blank and "CC" is filled then it throw bad request error. If CC and To field are filled with same email id then again it failed with bad request. Is this by design or it is a bug.

Thanks

**Comment by shwetha-manvinkurke** [comment] 2021-03-23 21:40
@gill1986 that is by design. Why would you want to send a mail with only a 'Cc' and not a 'To' and why would you want to send a mail with both 'Cc' and 'To' fields as the same address?

**Comment by gill1986** [comment] 2021-03-25 08:05
Our existing design was working like this, we were using SMTP but now on azure we are planning to use SendGrid.

**Comment by thinkingserious** [comment] 2021-03-30 22:56
Hello @gill1986,

With the v3 Web API the `to` field is required and you can not have duplicate emails within the `to`, `cc` and `bcc` fields. ([docs](https://sendgrid.api-docs.io/v3.0/mail-send/v3-mail-send))

Could you give us a bit of context around your use case so that we may offer potential solutions(s)? 

Thank you!

With best regards,

Elmer

**Comment by eshanholtz** [comment] 2021-05-04 22:23
I'm closing this issue until feedback is addressed.

**Closed by eshanholtz** 2021-05-04 22:23 UTC
Labels: status: waiting for feedback, type: question
