### ISSUE TITLE
Attachments with accents in the name result in an error from SendGrid

### ISSUE THREAD

**Issue by dtarachan** [sendgrid/sendgrid-csharp#54] opened 2014-04-11 17:23 UTC
When sending attachments with accents in the file name, SendGrid responds with the following error:

```XML
<result>
  <message>error</message>
  <errors>
    <error>Parameter =?utf-8?B?ZmlsZXNbTVBHw5bDicOLLnBkZl0=?= is not utf8</error>
  </errors>
 </result>
```

Sample code for adding the attachment to reproduce the error above is:

```C#
mailMessage.AddAttachment(fs, "MPGÖÉË.pdf");
```

Is this a bug in the library or with SendGrid? Or should the file name be encoded or escaped in some way?

Thanks.

**Comment by brandonmwest** [comment] 2015-02-07 19:26
I'm closing this because I've determined we can't address it at the library level. Still working on getting it fixed.

**Closed by brandonmwest** 2015-02-07 19:26 UTC

**Comment by janus007** [comment] 2015-09-20 17:49
Hello
I need to ask, is there any progress in this bug?

Cheers
Janus

**Comment by HugCoder** [comment] 2016-02-02 13:51
Yep, still not fixed. I'm using C# Sendgrid and I try to send a an attachment containing the Swedish letter Ö and the received mail isn't containing any attachment at all.

**Comment by thinkingserious** [comment] 2016-02-02 16:41
@HugCoder, @janus007  Could you both please report this issue over at support@sendgrid.com? That would be very helpful toward gaining resolution. Thanks!

**Comment by HugCoder** [comment] 2016-02-23 21:36
@thinkingserious OK, I reported it to them now. It's not a "game breaking" issue for me, but it would of course be nice and perhaps more modern to support UTF-8 names. ANSI only feels pretty outdated these days.

**Comment by thinkingserious** [comment] 2016-02-23 21:43
Thank you!

**Comment by HugCoder** [comment] 2016-02-23 22:20
I already got an answer:
"
We are aware of the issue of attachments with special characters not working. Unfortunately I don't have a timeline of of when it will be fixed. Thank you for keeping us informed about this and I will pass it on.
"
So, they are aware and working on it! Nice to hear!

**Comment by ShieldPad** [comment] 2016-05-04 09:14
Would be great if you could fix this :-)

There are email addresses with the Swedish 'ö' which I can't get to work with the sendgrid API. This means that a portion of our recepients can never receive emails from Sendgrid.

**Comment by markbarkell** [comment] 2016-09-29 23:54
@brandonmwest is on a very good track mentioning RFC 2047.   I was able to use RFC 2047 section 2, Syntax Of Encoded Words, in order to attach emails whose file name had an umlaut vowel.

What I did, using the C# functionality, was to 

string encodedFileName = "=?UTF-8?B?" + Convert.ToBase64String(UTF8Encoding.UTF8.GetBytes("namewithspecials.pdf")) + "?=";

into the 
message's AddAttachment(stream, encodedFileName) method.

This technique also works when rolling headers more manually with the Content-Disposition and the Name property  "file[" + encodedFileName + "]".

I do not know whether it would work for the "To" header.  I've not considered that in reading any RFC's.

Of course, when and if the API is "fixed" it will have to consider these types of workarounds.

**Comment by thinkingserious** [comment] 2016-10-04 20:03
Thanks for sharing a workaround @markbarkell!

Do you mind emailing us at dx@sendgrid.com with your mailing address, phone number and T-shirt size, so we can send you some swag?

**Comment by kekwin** [comment] 2017-02-21 13:02
Still seems there is an issue with special characters "Æ,Ø,Å" in attachment file names. Hope to see it resolved at some point.

**Comment by thinkingserious** [comment] 2017-02-21 16:11
Hi @kekwin,

Do you mind opening a new ticket with the code that you are having trouble with? 

I was unable to reproduce with the following code:

```csharp
using SendGrid;
using SendGrid.Helpers.Mail;
using System;
using System.Threading.Tasks;
using System.IO;

namespace Example
{
	internal class Example
	{
		private static void Main()
		{
			Execute().Wait();
		}

		static async Task Execute()
		{
			var apiKey = Environment.GetEnvironmentVariable("SENDGRID_API_KEY");
			var client = new SendGridClient(apiKey);
			var from = new EmailAddress("dx@sendgrid.com");
			var subject = "Subject";
			var to = new EmailAddress("elmer.thomas@sendgrid.com");
			var body = "Email Body";
			var msg = MailHelper.CreateSingleEmail(from, to, subject, body, "");
			var bytes = File.ReadAllBytes("/temp/ÆØÅ.txt");
			var file = Convert.ToBase64String(bytes);
			msg.AddAttachment("ÆØÅ.txt", file);
			var response = await client.SendEmailAsync(msg);
		}
	}
}
```

**Comment by petero-dk** [comment] 2018-10-02 11:03
I have this issue with ÆØÅ in Xamarin projects on Android (have not tested with iOS). I am testing the solution from @markbarkell this moment. I do not know if I can take out a sample to test, but I thought it would be prudent to inform that with ÆØÅ in the file name no attachments are delivered, while without we experience no problems. And differentiating from the sample above we are on Xamarin.

**Comment by thinkingserious** [comment] 2018-10-03 21:07
Thanks for the heads up @petero-dk! If @markbarkell's solution does not work for you, please create a new issue in this repo.

With Best Regards,

Elmer
