### ISSUE TITLE
HttpClient - wrong usage in library

### ISSUE THREAD

**Issue by jonnybee** [sendgrid/sendgrid-csharp#413] opened 2017-03-06 13:56 UTC
SendGridClient always create a new HttpClient and then dispose this object for each request. 
This is wrong usage of HttpClient and may lead to instability in performance. 

See: https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/ 
and https://blogs.msdn.microsoft.com/henrikn/2012/02/16/httpclient-is-here/ 
(and also read the comments on the last article)

**Comment by xt0rted** [comment] 2017-03-06 16:40
Duplicate of #405

**Comment by thinkingserious** [comment] 2017-03-07 07:47
Hi @jonnybee,

I've added your vote to issue #405.

Thanks!

**Closed by thinkingserious** 2017-03-07 07:47 UTC
Labels: status: duplicate, type: question
